sonarqube:
  container_name: sonarqube_web
  image: sonarqube:6.0-alpine
  ports:
   - "9000:9000"
  links:
    - postgresql:db
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=xaexohquaetiesoo
  volumes_from:
   - plugins
  restart: always 

plugins:
  container_name: sonarqube_plugins
  image: sonarqube:6.0-alpine
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true

install_plugins:
  container_name: sonarqube_install_plugins
  build: plugins
  volumes_from:
   - plugins
  restart: never

postgresql:
  container_name: sonarqube_db
  image: orchardup/postgresql:latest
  environment:
    - POSTGRESQL_USER=sonar
    - POSTGRESQL_PASS=xaexohquaetiesoo
    - POSTGRESQL_DB=sonar
  volumes:
    - ./sonarqube/data:/var/lib/postgresql
  ports:
    - "5432:5432"
