---
version: '2'

services:
  sonarqube:
    container_name: sonarqube_web
    depends_on:
      - install_plugins
      - plugins
      - postgresql
    image: sonarqube:6.0-alpine
    ports:
     - "9000:9000"
    links:
      - postgresql:db
    env_file:
      - ./env/web.env
      - ./env/web.secrets.env
    volumes_from:
     - plugins
    restart: always 

  plugins:
    container_name: sonarqube_plugins
    image: sonarqube:6.0-alpine
    volumes:
     - /opt/sonarqube/extensions
     - /opt/sonarqube/lib/bundled-plugins
    command: /bin/true

  install_plugins:
    container_name: sonarqube_install_plugins
    build: plugins
    volumes_from:
     - plugins
    restart: never

  postgresql:
    container_name: sonarqube_db
    image: orchardup/postgresql:latest
    env_file:
      - ./env/db.env
      - ./env/db.secrets.env
    volumes:
      - ./sonarqube/data:/var/lib/postgresql
    ports:
      - "5432:5432"

